development:
  adapter: postgresql
  encoding: unicode
  database: exchange_rates_dev
  pool: 5
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: exchange_rates_test
  pool: 5
  username: postgres



